#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create mesh
runApplication blockMesh

# initialise with potentialFoam solution
runApplication potentialFoam
rm -f 0/phi

# run the solver
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
