#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy 0 directory
cp -r 0.org 0

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet

runApplication setFields

runApplication decomposePar
rm -rf log.topoSet
runParallel topoSet 4
runParallel `getApplication` 4
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
