#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake
wmake rhoPorousMRFPimpleFoam
wmake rhoPorousMRFLTSPimpleFoam

# ----------------------------------------------------------------- end-of-file
