#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

runApplication blockMesh
transformPoints -scale '(1.6666 1 1)'

cp system/changeDictionaryDict.X system/changeDictionaryDict
runApplication changeDictionary -instance system
runApplication mirrorMesh
rm log.mirrorMesh

rm log.changeDictionary
cp system/changeDictionaryDict.Y system/changeDictionaryDict
runApplication changeDictionary -instance system

runApplication mirrorMesh
cp -rf 0/polyMesh constant/

runApplication topoSet
runApplication createPatch -overwrite
runApplication $application

# ----------------------------------------------------------------- end-of-file
