#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

foamCleanTutorials cases
rm -rf processor*
rm -rf 0/p_rgh 0/p_rgh.gz 0/alpha1 0/alpha1.gz

# ----------------------------------------------------------------- end-of-file
