#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType field
wmake $makeType forces
wmake $makeType IO
wmake $makeType utilities
wmake $makeType jobControl
wmake $makeType systemCall

# ----------------------------------------------------------------- end-of-file
