#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication setFields

unset FOAM_SIGFPE
unset FOAM_SETNAN

# Create faceZones for porous baffles
runApplication topoSet

createBaffles cyclicZoneFaces '(porous_half0 porous_half1)' -overwrite > log.createBaffles 2>&1

runApplication changeDictionary

runApplication $application

# ----------------------------------------------------------------- end-of-file
